"""add valuation_properties table

Revision ID: 4e331715de18
Revises: 7499f8f1ab73
Create Date: 2026-09-17 15:29:21.613322

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e331715de18'
down_revision: Union[str, Sequence[str], None] = '7499f8f1ab73'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('valuation_properties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=False),
    sa.Column('property_type', sa.String(length=24), nullable=False),
    sa.Column('address', sa.String(length=200), nullable=True),
    sa.Column('nta_code', sa.String(length=8), nullable=True),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('sqft', sa.Float(), nullable=True),
    sa.Column('bedrooms', sa.Float(), nullable=True),
    sa.Column('common_charges', sa.Float(), nullable=True),
    sa.Column('property_taxes', sa.Float(), nullable=True),
    sa.Column('rent_estimate', sa.Float(), nullable=True),
    sa.Column('assumption_overrides', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['nta_code'], ['neighborhoods.code'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('valuation_properties', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_valuation_properties_nta_code'), ['nta_code'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('valuation_properties', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_valuation_properties_nta_code'))

    op.drop_table('valuation_properties')
    # ### end Alembic commands ###
