"""baseline schema

Revision ID: 7499f8f1ab73
Revises: 
Create Date: 2026-09-17 00:22:31.906234

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7499f8f1ab73'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_settings',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('neighborhoods',
    sa.Column('code', sa.String(length=8), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('borough', sa.String(length=20), nullable=False),
    sa.Column('residential', sa.Boolean(), nullable=False),
    sa.Column('geometry', sa.JSON(), nullable=False),
    sa.Column('area_km2', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('sales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bbl', sa.String(length=10), nullable=False),
    sa.Column('building_key', sa.String(length=16), nullable=False),
    sa.Column('address', sa.String(length=200), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=True),
    sa.Column('zip_code', sa.String(length=5), nullable=True),
    sa.Column('nta_code', sa.String(length=8), nullable=True),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('sale_date', sa.Date(), nullable=False),
    sa.Column('year_built', sa.Integer(), nullable=True),
    sa.Column('category', sa.String(length=80), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bbl', 'sale_date', 'price')
    )
    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sales_bbl'), ['bbl'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_building_key'), ['building_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_nta_code'), ['nta_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_sale_date'), ['sale_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_zip_code'), ['zip_code'], unique=False)

    op.create_table('source_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('records', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('source_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_source_runs_source'), ['source'], unique=False)

    op.create_table('listings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('external_id', sa.String(length=128), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.Column('address', sa.String(length=200), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=True),
    sa.Column('zip_code', sa.String(length=5), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('bbl', sa.String(length=10), nullable=True),
    sa.Column('nta_code', sa.String(length=8), nullable=True),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('original_price', sa.Float(), nullable=False),
    sa.Column('bedrooms', sa.Float(), nullable=True),
    sa.Column('bathrooms', sa.Float(), nullable=True),
    sa.Column('sqft', sa.Float(), nullable=True),
    sa.Column('year_built', sa.Integer(), nullable=True),
    sa.Column('common_charges', sa.Float(), nullable=True),
    sa.Column('property_taxes', sa.Float(), nullable=True),
    sa.Column('rent_estimate', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('listed_date', sa.Date(), nullable=False),
    sa.Column('first_seen', sa.DateTime(), nullable=False),
    sa.Column('last_seen', sa.DateTime(), nullable=False),
    sa.Column('missed_fetches', sa.Integer(), nullable=False),
    sa.Column('off_market_date', sa.Date(), nullable=True),
    sa.Column('sold_date', sa.Date(), nullable=True),
    sa.Column('sold_price', sa.Float(), nullable=True),
    sa.Column('sold_document_id', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['nta_code'], ['neighborhoods.code'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'external_id')
    )
    with op.batch_alter_table('listings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_listings_bbl'), ['bbl'], unique=False)
        batch_op.create_index(batch_op.f('ix_listings_nta_code'), ['nta_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_listings_status'), ['status'], unique=False)

    op.create_table('neighborhood_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nta_code', sa.String(length=8), nullable=False),
    sa.Column('metric', sa.String(length=64), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('as_of', sa.String(length=32), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['nta_code'], ['neighborhoods.code'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nta_code', 'metric')
    )
    with op.batch_alter_table('neighborhood_metrics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_neighborhood_metrics_metric'), ['metric'], unique=False)
        batch_op.create_index(batch_op.f('ix_neighborhood_metrics_nta_code'), ['nta_code'], unique=False)

    op.create_table('neighborhood_scores',
    sa.Column('nta_code', sa.String(length=8), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('pillars', sa.JSON(), nullable=False),
    sa.Column('coverage', sa.Float(), nullable=False),
    sa.Column('computed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['nta_code'], ['neighborhoods.code'], ),
    sa.PrimaryKeyConstraint('nta_code')
    )
    op.create_table('listing_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('listing_id', sa.Integer(), nullable=False),
    sa.Column('observed_at', sa.DateTime(), nullable=False),
    sa.Column('event', sa.String(length=24), nullable=False),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('listing_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_listing_snapshots_listing_id'), ['listing_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listing_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_listing_snapshots_listing_id'))

    op.drop_table('listing_snapshots')
    op.drop_table('neighborhood_scores')
    with op.batch_alter_table('neighborhood_metrics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_neighborhood_metrics_nta_code'))
        batch_op.drop_index(batch_op.f('ix_neighborhood_metrics_metric'))

    op.drop_table('neighborhood_metrics')
    with op.batch_alter_table('listings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_listings_status'))
        batch_op.drop_index(batch_op.f('ix_listings_nta_code'))
        batch_op.drop_index(batch_op.f('ix_listings_bbl'))

    op.drop_table('listings')
    with op.batch_alter_table('source_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_source_runs_source'))

    op.drop_table('source_runs')
    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sales_zip_code'))
        batch_op.drop_index(batch_op.f('ix_sales_sale_date'))
        batch_op.drop_index(batch_op.f('ix_sales_nta_code'))
        batch_op.drop_index(batch_op.f('ix_sales_building_key'))
        batch_op.drop_index(batch_op.f('ix_sales_bbl'))

    op.drop_table('sales')
    op.drop_table('neighborhoods')
    op.drop_table('app_settings')
    # ### end Alembic commands ###
