"""add area model for US-wide geographies

Revision ID: 998d59045064
Revises: 858fc604a4bb
Create Date: 2026-09-17 22:57:09.937723

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '998d59045064'
down_revision: Union[str, Sequence[str], None] = '858fc604a4bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('regions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=8), nullable=False),
    sa.Column('code', sa.String(length=12), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('state_fips', sa.String(length=2), nullable=True),
    sa.Column('watched', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kind', 'code')
    )
    with op.batch_alter_table('regions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_regions_code'), ['code'], unique=False)

    op.create_table('areas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=8), nullable=False),
    sa.Column('code', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('state_fips', sa.String(length=2), nullable=True),
    sa.Column('county_fips', sa.String(length=5), nullable=True),
    sa.Column('cbsa', sa.String(length=5), nullable=True),
    sa.Column('residential', sa.Boolean(), nullable=False),
    sa.Column('geometry', sa.JSON(), nullable=True),
    sa.Column('area_km2', sa.Float(), nullable=True),
    sa.Column('nta_code', sa.String(length=8), nullable=True),
    sa.ForeignKeyConstraint(['nta_code'], ['neighborhoods.code'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kind', 'code')
    )
    with op.batch_alter_table('areas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_areas_cbsa'), ['cbsa'], unique=False)
        batch_op.create_index(batch_op.f('ix_areas_code'), ['code'], unique=False)
        batch_op.create_index(batch_op.f('ix_areas_county_fips'), ['county_fips'], unique=False)
        batch_op.create_index(batch_op.f('ix_areas_kind'), ['kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_areas_nta_code'), ['nta_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_areas_state_fips'), ['state_fips'], unique=False)

    op.create_table('area_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('area_id', sa.Integer(), nullable=False),
    sa.Column('metric', sa.String(length=64), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('as_of', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['area_id'], ['areas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('area_id', 'metric')
    )
    with op.batch_alter_table('area_metrics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_area_metrics_area_id'), ['area_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_area_metrics_metric'), ['metric'], unique=False)

    op.create_table('area_scores',
    sa.Column('area_id', sa.Integer(), nullable=False),
    sa.Column('comparison_set', sa.String(length=32), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('pillars', sa.JSON(), nullable=False),
    sa.Column('coverage', sa.Float(), nullable=False),
    sa.Column('computed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['area_id'], ['areas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('area_id')
    )
    with op.batch_alter_table('area_scores', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_area_scores_comparison_set'), ['comparison_set'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('area_scores', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_area_scores_comparison_set'))

    op.drop_table('area_scores')
    with op.batch_alter_table('area_metrics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_area_metrics_metric'))
        batch_op.drop_index(batch_op.f('ix_area_metrics_area_id'))

    op.drop_table('area_metrics')
    with op.batch_alter_table('areas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_areas_state_fips'))
        batch_op.drop_index(batch_op.f('ix_areas_nta_code'))
        batch_op.drop_index(batch_op.f('ix_areas_kind'))
        batch_op.drop_index(batch_op.f('ix_areas_county_fips'))
        batch_op.drop_index(batch_op.f('ix_areas_code'))
        batch_op.drop_index(batch_op.f('ix_areas_cbsa'))

    op.drop_table('areas')
    with op.batch_alter_table('regions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_regions_code'))

    op.drop_table('regions')
    # ### end Alembic commands ###
